version: '3.3'

services:
  set-sg-desc.py:
    image: himaoka/set-sg-desc
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
    volumes:
      - .:/src
      - ~/.aws:/root/.aws
    working_dir: /src
